--2023.04.13
-- JOIN 할듯


SELECT TO_NUMBER(MGR) FROM EMP;

--두번째 문자 기준에서 다섯번째 자리까지 뽑아준다.
SELECT SUBSTR('801212-10245678' , 2 , 5) FROM DUAL;

SELECT TO_CHAR(SYSDATE , 'YY-MM-DD') FROM DUAL;


SELECT DEPTNO , COUNT(*) FROM EMP GROUP BY DEPTNO;

SELECT DEPTNO , COUNT(*) ,AVG(SAL) ,MAX(SAL)
FROM EMP 
GROUP BY DEPTNO
HAVING MAX(SAL) > 2900;

